### ISSUE TITLE
Source code questions

### ISSUE THREAD

**Issue by mrjoelkemp** [mdevils/cst#23]
https://github.com/mdevils/cst/blob/master/src/elementTree.js#L10-L91 could be replaced with https://github.com/jscs-dev/babel-jscs/blob/aeccaae43660db17549e95c8b3ec8a7b00df1389/index.js#L6 which are these: https://github.com/babel/babel/blob/bb5f1120b79c086256b270182f2bd232b89d4276/src/babel/types/visitor-keys.json.

Any reason why we needed to duplicate them here?

**Comment by mdevils** [comment]
Hello Joel, I also found visitor-keys useful, right now duplication only exists for tracking what's done/tested, so it is a temporal duplication.

**Comment by mrjoelkemp** [comment]
Hope you don't mind the issues asking questions. There's no PR to leave comments on. I'll keep my questions to this thread to avoid creating multiple issues.

**Comment by mdevils** [comment]
I appreciate questions! Every non obvious thing is a reason for docs improval :)
